-- V1__initial_schema.sql

-- Initial schema matching the provided Alembic migration

-- Create tables with IDENTITY columns

CREATE TABLE USUARIOS_VITS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome_completo VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    cpf VARCHAR2(14) NOT NULL UNIQUE,
    senha_hash VARCHAR2(255) NOT NULL,
    data_cadastro TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE LOTES (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome_lote VARCHAR2(255) NOT NULL,
    cultura VARCHAR2(100) NOT NULL,
    producao_total NUMBER(15,2) NOT NULL,
    custo_total NUMBER(15,2) NOT NULL,
    preco_venda NUMBER(15,2) NOT NULL,
    status VARCHAR2(50) DEFAULT 'ativo' NOT NULL,
    usuario_id NUMBER NOT NULL,
    CONSTRAINT fk_lotes_usuario FOREIGN KEY (usuario_id) REFERENCES USUARIOS_VITS(id) ON DELETE CASCADE
);

CREATE TABLE EVENTOS_CULTIVO (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    lote_id NUMBER NOT NULL,
    tipo_evento VARCHAR2(100) NOT NULL,
    data_plantio DATE NOT NULL,
    data_colheita_estimada DATE NULL,
    descricao CLOB NULL,
    CONSTRAINT fk_eventos_lote FOREIGN KEY (lote_id) REFERENCES LOTES(id) ON DELETE CASCADE
);

CREATE TABLE SIMULACOES (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    lote_id NUMBER NULL,
    resultado CLOB NOT NULL,
    melhor_opcao VARCHAR2(50) NULL,
    CONSTRAINT fk_simulacoes_lote FOREIGN KEY (lote_id) REFERENCES LOTES(id) ON DELETE SET NULL
);

-- Indexes
CREATE INDEX idx_usuarios_email ON USUARIOS_VITS(email);
CREATE INDEX idx_lotes_usuario ON LOTES(usuario_id);
CREATE INDEX idx_eventos_lote ON EVENTOS_CULTIVO(lote_id);
CREATE INDEX idx_simulacoes_lote ON SIMULACOES(lote_id);
